
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - .:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - taxapp

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - taxapp

  app:
    depends_on:
      - db
      - webserver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "127.0.0.1:9000:9000"
    env_file:
      - ./.env
    networks:
      - taxapp

volumes:
  mysql_data:

networks:
  taxapp:
